name: Push to Shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'
        
    - name: Set up renv
      uses: r-lib/actions/setup-renv@v2
      
    - name: Set shinyapps.io credentials
      run: R -e 'rsconnect::setAccountInfo(name="cluffa", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")'
      
    - name: Deploy to shinyapps.io
      run: R -e 'rsconnect::deployApp(appDir = ".", forceUpdate = TRUE, launch.browser = FALSE)'